spring.thymeleaf.cache=false

gulimall.thread.coreSize=20
gulimall.thread.maxSize=200
gulimall.thread.keepAliveTime=10

# RabbitMQ配置
spring.rabbitmq.host=192.168.100.128
spring.rabbitmq.port=5672
# 虚拟主机配置
spring.rabbitmq.virtual-host=/
# 开启发送端消息抵达Broker确认
spring.rabbitmq.publisher-confirms=true
# 开启发送端消息抵达Queue确认
spring.rabbitmq.publisher-returns=true
# 只要消息抵达Queue，就会异步发送优先回调returnfirm
spring.rabbitmq.template.mandatory=true
# 手动ack消息，不使用默认的消费端确认
spring.rabbitmq.listener.simple.acknowledge-mode=manual

#支付宝相关的配置
alipay.app_id=9021000162640824
alipay.merchant_private_key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYwAPw8An5OzfwZqBPlNtQtP7k0h3P+5RA2QB+6MMmPiRxtt9+aRTlNtcmikZlD4bfCjPTooUK/3Mf6iQL3auShRqjel2zTu+KIHy63FOGc+/xWBIvaW0LBH8R9EqLGOj+ALAo0fISpJ2/CixpRaU7arWuQe/3kgUl8bzc/U1UQ206zPWVDxQ0YwSaJbSdzCNsZwCYw5JhebGbGFOKXYK2yTbqzXCpnCj8u3oLLS+0Nox71avMsF9ZG92/swYzS2psakE9f98MWEsLaBeVhOt5nKNRSAuYL4njiV/NlT0eWUQxDr2Gmwzu4ve7wYBMJyu+af1EvEBVm9o09yII/F2pAgMBAAECggEAeBIYBwDpFhzSsAo74dKlQx/DbaMtBBxCQWdS2G+nVxxqEWkq7Xc0kak2Hnl7NF2sKw8eBjIuWqLKoD+w7hLll1tBwVei6BwYd39qDIi8r2fbKN+OC+7XZF24dSiOoCCIpYFs9+lwW+9CgLVCi83PQJF1FvGF7BnAKj+Hsj761kygcwfl1ujic9oXnhsYIR7FdvC4Idd8zn67pDeQA0zr9ZRDKsgrUdlbV/sYUrM50do2AsDRug3/KAQc3+XYfc4mtAJ7h/wiAnEf0fkqTOMaJ+VVT/XbkzCmk5G/x7M4qttMOQYViBIlI5Mef0453EV95PdsXbuaHzjGOXP4kk3F8QKBgQDi0njTLgtz9MEeni073pELCUWQC0Tq/Kyi3xunuAPQjzPyPcRBJQq801Qsk26mF3z2qvdtuZwBjit+Khe7gW6ypXXXiixsPHXHDPLvnrq5ewhKluaGgG3cjwAXQyLRNPyvGddshKxaxdq5nAdW58o+cbbVCmJ7tTBRCFHxtUUYYwKBgQCsZkJ6n7XrM8hnQ+7R73qCzUjXU1sALQcMiH0jHHLI5tdvp8qkIMfSIDAuaRO6qgC6ETyZBNQyRXJOlthpoCiB8Est/yPF06pzSBkkg9opWlDbaj1diB82AW11Vks4vK13wArl1pTiWq84w8+VabF+gtbPeE70ncgoLo/9T32BgwKBgG2qISzJSFRJ880f4PLfSvUxCGb6a9nJTJZ6lF5kw8NkWVM3tdlhVW2yJzJeHdND6/E++94bLWg7GqAnLc5EaAcLpIwPjCbQnIkeo55i+hiPeZTGnLJPCc7nfL3CgeTwX3MxZUxcYRCKNJQk8g98hfXm+OTL3o29Lp0fDq90WvHNAoGBAI77WNN+tlBV6DXNH7s51O+69livp1+j+J6qbK68H28EFVVjYitxjIh3bb5wI47DBEtNlGaMnLj84+rOLLqdvDrYYmHJo4+lF075UvD38e4uG7V+jVqPVONjl7ajVUu/IFebDO7GY0DAWWbI79dJi44TUblMXJ+AZMr+oylBziOlAoGAE0Nzy/ZUvI+UKjjbjgnCJdZDwFJ1XCEJlJ1nbifyO2Cj1C/lTfmUEosbSFs4keRfgaD3iHDrIZ4Zd5XMECbzzduI5ZYSKzQblRPqGBuvmg4uOUsi3eqey8thEnLHNM2zGvsyfz6g8Dr/D7VfXA1L/6FkvLZNJWGUQIJNOWsMHfw=
alipay.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj8LSEwdsqvnKa6H+xgjTWAwoOkMTixPyQFp7fQ3+MapO9qrKHdrh8rPO6wva+s1PH0jROfRaeYqrf/4fZIfLr/i+pt/f65OchTG9UyBsm/UhLIB2P4IcY9KdTkerNzsYbzTuQDiNTGCndioA6UhKgfePRkq279i/Y7BYphtz8D6UKNUmqLzHA0jqeEFfsvHH4cpo90tVu6TLU/snPuIEnS5PqoZXkDpuULvXKkpXjJSKT4bFNzJJSC9r/6Xjfa2mhlLFJYXhFM3b/fAEsyupIRyAz62hh9A1HMU5eYr+Ehhm9GSe2hWoj7KPZZM7ezcTQYi91Ox4Qx7R2FCgBabYZQIDAQAB
#alipay.notify_url=http://hjl.mynatapp.cc/payed/notify
alipay.notify_url=http://tzy.nat300.top/payed/notify
alipay.return_url=http://member.gulimall.com/memberOrder.html
alipay.sign_type=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do


#微信相关配置
wx.appId=wxd898fcb01713c658
wx.mchId=1483469312
wx.mchKey=098F6BCD4621D373CADE4E832627B4F6
wx.notifyUrl=http://hjl.mynatapp.cc/pay/notify
wx.returnUrl=http://member.gulimall.com/memberOrder.html

spring.mvc.date-format=yyyy-MM-dd HH:mm:ss


#服务追踪
spring.zipkin.base-url=http://192.168.100.128:9411/
#关闭服务发现
spring.zipkin.discovery-client-enabled=false
spring.zipkin.sender.type=web
#配置采样器
spring.sleuth.sampler.probability=1